'use strict';
const $=id=>document.getElementById(id);
const safeStore={get(k,d=null){try{const v=localStorage.getItem(k);return v===null?d:v}catch{return d}},set(k,v){try{localStorage.setItem(k,String(v));return true}catch{return false}},del(k){try{localStorage.removeItem(k)}catch{}}};
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const categories=[
{name:'安全・安心',icon:'🛟',subs:['防災','消防・救急','防犯','交通安全','災害情報','国民保護','消費生活','安全安心メール']},
{name:'くらし・手続き',icon:'🏠',subs:['戸籍・住民票','引越し','マイナンバー','税金','ごみ・リサイクル','上下水道','電子申請','各種証明','相談窓口']},
{name:'子育て・教育',icon:'👶',subs:['妊娠・出産','保育園','幼稚園','子育て支援','学校教育','学童保育','児童手当','青少年']},
{name:'健康・福祉',icon:'🏥',subs:['休日当番医','健康診査','予防接種','高齢者支援','介護保険','障害福祉','生活支援','国民健康保険','年金']},
{name:'観光・文化・スポーツ',icon:'🎪',subs:['観光','イベント','文化財','図書館','公民館','スポーツ','市民会館','施設予約']},
{name:'まちづくり・環境',icon:'🌳',subs:['都市計画','公園','道路','住宅','空き家','環境','自然保護','そでMAP','公共施設']},
{name:'仕事・産業',icon:'🏭',subs:['企業立地','商工業','農業','就職','入札・契約','創業支援','産業振興','事業者支援']},
{name:'市政情報',icon:'🏛',subs:['組織・担当課','予算・決算','議会','市長','広報','市民の声','パブリックコメント','計画・政策','オープンデータ']}
];
const needs=[['🗑','ごみを出したい','分別・収集・粗大ごみ'],['🏠','引っ越した','転入・転出・住所変更'],['📄','証明書がほしい','住民票・戸籍・税証明'],['👶','子育てを調べたい','妊娠・保育・手当'],['🏥','病院を探したい','休日・夜間診療'],['🛟','避難所を知りたい','防災・ハザード'],['🚌','移動したい','鉄道・バス・自動運転'],['👵','高齢者支援を知りたい','介護・移動・生活支援']];
const routes=[
{keys:['ごみ','ゴミ','粗大','廃棄'],title:'ごみ・粗大ごみ',text:'分別・収集日・粗大ごみの公式情報へ進みます。',url:'https://www.city.sodegaura.lg.jp/life/12/'},
{keys:['避難','避難所','防災','浸水','災害','ハザード'],title:'防災・避難',text:'避難所・ハザード・防災情報を確認します。',url:'https://www.city.sodegaura.lg.jp/life/11/'},
{keys:['住民票','戸籍','引越','引っ越','転入','転出','住所変更'],title:'くらし・手続き',text:'住民票・戸籍・住所変更を確認します。',url:'https://www.city.sodegaura.lg.jp/life/12/'},
{keys:['バス','交通','移動','自動運転','電車','鉄道'],title:'交通・モビリティ',text:'自動運転バスなど移動情報へ進みます。',url:'https://www.city.sodegaura.lg.jp/site/autonomousbus/'},
{keys:['病院','医療','休日当番医','診療','救急'],title:'健康・医療',text:'休日・夜間診療や健康情報を確認します。',url:'https://www.city.sodegaura.lg.jp/life/14/'},
{keys:['子育て','保育','妊娠','出産','児童'],title:'子育て・教育',text:'妊娠、保育、子育て支援を確認します。',url:'https://www.city.sodegaura.lg.jp/life/13/'},
{keys:['市役所','窓口','庁舎','市庁舎'],title:'市庁舎 Digital Twin',text:'棟・階・窓口候補・公式確認へ進みます。',url:'./cityhall.html'}];
const synonymGroups=[['ごみ','ゴミ'],['引越','引っ越し','引っ越'],['病院','医療','診療'],['避難所','避難','防災'],['バス','交通','移動'],['市役所','庁舎','市庁舎']];
function normalize(s){return String(s||'').trim().toLowerCase().normalize('NFKC').replace(/[\s　・,，。\.\/／_-]+/g,'')}
function expandTerms(raw){const n=normalize(raw);if(!n)return[];const terms=[n];synonymGroups.forEach(g=>{if(g.some(x=>n.includes(normalize(x))))g.forEach(x=>terms.push(normalize(x)))});return[...new Set(terms)]}
function routeMatches(text){const terms=expandTerms(text);return routes.map(r=>{let score=0;r.keys.forEach(k=>{const nk=normalize(k);if(terms.some(q=>q.includes(nk)||nk.includes(q)))score+=nk.length>2?2:1});return{...r,score}}).filter(r=>r.score>0).sort((a,b)=>b.score-a.score||a.title.localeCompare(b.title,'ja'))}
function routeLink(r){const ext=r.url.startsWith('http');return`<a href="${r.url}" ${ext?'target="_blank" rel="noopener noreferrer"':''}>${escapeHtml(r.title)} →</a>`}
function runAI(text){const hits=routeMatches(text),box=$('aiAnswer');if(!hits.length){box.innerHTML='<strong>候補を絞り込めませんでした</strong><br>「ごみ」「避難所」「住民票」「バス」「病院」「子育て」「市役所」など目的を短く入力してください。';box.classList.add('show');return}const top=hits[0];let html=`<strong>${escapeHtml(top.title)}</strong><br>${escapeHtml(top.text)}<br>${routeLink(top)}`;const alternatives=hits.slice(1,4);if(alternatives.length)html+=`<br><small>関連候補: ${alternatives.map(routeLink).join(' / ')}</small>`;box.innerHTML=html;box.classList.add('show')}
function renderNeeds(){const box=$('needsGrid');box.textContent='';needs.forEach(n=>{const b=document.createElement('button');b.type='button';b.className='card need searchable';b.dataset.search=`${n[1]} ${n[2]}`;b.innerHTML=`<span>${n[0]}</span><b>${escapeHtml(n[1])}</b><small>${escapeHtml(n[2])}</small>`;b.onclick=()=>runAI(n[1]);box.appendChild(b)})}
function renderAdmin(){const box=$('adminCards');box.textContent='';categories.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='card adminCard searchable';b.dataset.search=[c.name,...c.subs].join(' ');b.innerHTML=`<span>${c.icon}</span><strong>${escapeHtml(c.name)}</strong><small>${c.subs.map(escapeHtml).join(' / ')}</small>`;b.onclick=()=>runAI(c.name);box.appendChild(b)})}
function searchMatch(haystack,q){const h=normalize(haystack),terms=expandTerms(q);return !terms.length||terms.some(t=>h.includes(t))}
function applySearch(q){let count=0;document.querySelectorAll('.searchable').forEach(el=>{const on=searchMatch(el.dataset.search,q);el.hidden=!on;if(on)count++});$('resultCount').textContent=count+'件';$('emptyState').classList.toggle('show',count===0);safeStore.set('sr-search',q)}
function setView(v,focus=false){['admin','needs','dx'].forEach(x=>$(x+'View').hidden=x!==v);document.querySelectorAll('[data-view]').forEach(b=>{const on=b.dataset.view===v;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1;if(on&&focus)b.focus()});safeStore.set('sr-view',v)}
const tabs=[...document.querySelectorAll('[data-view]')];tabs.forEach((b,i)=>{b.onclick=()=>setView(b.dataset.view);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=i;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i-1+tabs.length)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;setView(tabs[n].dataset.view,true)}});
function arrowGroup(selector,activate){const items=[...document.querySelectorAll(selector)];items.forEach((b,i)=>b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=i;if(e.key==='ArrowRight')n=(i+1)%items.length;if(e.key==='ArrowLeft')n=(i-1+items.length)%items.length;if(e.key==='Home')n=0;if(e.key==='End')n=items.length-1;items[n].focus();activate(items[n])}))}
function setPress(id,on){$(id)?.setAttribute('aria-pressed',String(on))}
function setBodyMode(cls,id,on){document.body.classList.toggle(cls,on);setPress(id,on);safeStore.set('sr-'+cls,on)}
[['a11y','a11yBtn'],['dark','darkBtn'],['lowdata','lowBtn']].forEach(([cls,id])=>{const on=safeStore.get('sr-'+cls)==='true';setBodyMode(cls,id,on);$(id).onclick=()=>setBodyMode(cls,id,!document.body.classList.contains(cls))});
function setEmergency(on){$('emergency').hidden=!on;$('emergencyPanel').hidden=!on;setPress('emBtn',on);safeStore.set('sr-emergency',on)}
setEmergency(safeStore.get('sr-emergency')==='true');$('emBtn').onclick=()=>setEmergency($('emergency').hidden);$('resetPrefs').onclick=()=>{['a11y','dark','lowdata'].forEach((c,i)=>setBodyMode(c,['a11yBtn','darkBtn','lowBtn'][i],false));setEmergency(false);['sr-view','sr-search','sr-layers','sr-zone','sr-year','sr-scenario'].forEach(k=>safeStore.del(k));$('siteSearch').value='';applySearch('');activeLayers.clear();selectedZone='';year='2026';scenario='基準';renderTwin();futureRender();syncStateUrl()};
$('aiGo').onclick=()=>runAI($('aiInput').value);$('aiInput').onkeydown=e=>{if(e.key==='Enter')runAI(e.currentTarget.value)};document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{$('aiInput').value=b.textContent;runAI(b.textContent)});document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{$('siteSearch').value=b.dataset.q;applySearch(b.dataset.q);runAI(b.dataset.q)});$('siteSearch').oninput=e=>applySearch(e.target.value);
const allowedLayers=new Set([...document.querySelectorAll('[data-layer]')].map(b=>b.dataset.layer));let activeLayers=new Set((safeStore.get('sr-layers','')||'').split('|').filter(x=>allowedLayers.has(x)));let selectedZone=safeStore.get('sr-zone','');
function syncStateUrl(){const u=new URL(location.href);activeLayers.size?u.searchParams.set('layers',[...activeLayers].join(',')):u.searchParams.delete('layers');selectedZone?u.searchParams.set('zone',selectedZone):u.searchParams.delete('zone');year!=='2026'?u.searchParams.set('year',year):u.searchParams.delete('year');scenario!=='基準'?u.searchParams.set('scenario',scenario):u.searchParams.delete('scenario');history.replaceState(null,'',u)}
function renderTwin(){document.querySelectorAll('[data-layer]').forEach(b=>b.setAttribute('aria-pressed',String(activeLayers.has(b.dataset.layer))));safeStore.set('sr-layers',[...activeLayers].join('|'));safeStore.set('sr-zone',selectedZone);let text=activeLayers.size?`表示レイヤー: ${[...activeLayers].join(' / ')}`:'レイヤー未選択';if(selectedZone)text+=`｜地区: ${selectedZone}`;$('twinInfo').textContent=text+'。本番では出典・更新日時・KPIを連動表示します。';syncStateUrl()}
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{const k=b.dataset.layer;activeLayers.has(k)?activeLayers.delete(k):activeLayers.add(k);renderTwin()});$('layerReset').onclick=()=>{activeLayers.clear();selectedZone='';renderTwin()};document.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{selectedZone=b.dataset.zone;renderTwin()});arrowGroup('[data-layer]',b=>b.click());
const future={2026:['人口 現在','高齢化 現在','交通 現況','空き家 現況','満足度 現況'],2030:['人口 中期','高齢化 中期','交通 改善案','空き家 対策','満足度 KPI'],2035:['人口 推計レンジ','高齢化 需要','交通 再設計','空き家 再生','満足度 目標'],2040:['人口 長期レンジ','高齢化 長期','交通 長期','施設 再編','満足度 長期']};let year=safeStore.get('sr-year','2026'),scenario=safeStore.get('sr-scenario','基準');if(!future[year])year='2026';if(!['基準','改善','課題'].includes(scenario))scenario='基準';
function futureRender(){document.querySelectorAll('[data-year]').forEach(b=>{const on=b.dataset.year===year;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.tabIndex=on?0:-1});document.querySelectorAll('[data-scenario]').forEach(b=>{const on=b.dataset.scenario===scenario;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.tabIndex=on?0:-1});$('futureTitle').textContent=`${year} / ${scenario}`;$('futureMetrics').innerHTML=future[year].map(x=>{const [a,...r]=x.split(' ');return `<div class="fm"><b>${escapeHtml(a)}</b><small>${escapeHtml(r.join(' '))}・${escapeHtml(scenario)}</small></div>`}).join('');safeStore.set('sr-year',year);safeStore.set('sr-scenario',scenario);syncStateUrl()}
document.querySelectorAll('[data-year]').forEach(b=>b.onclick=()=>{year=b.dataset.year;futureRender()});document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>{scenario=b.dataset.scenario;futureRender()});arrowGroup('[data-year]',b=>b.click());arrowGroup('[data-scenario]',b=>b.click());
function localDateKey(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}
const questKey='sr-quest-'+localDateKey();let xp=Math.max(0,Math.min(1000000,Number(safeStore.get('sr-xp','0'))||0));function questRender(){const done=safeStore.get(questKey)==='done';$('questDone').disabled=done;$('questDone').textContent=done?'本日は完了済み':'完了 +10 XP';$('xpText').textContent='地域XP '+xp}$('questDone').onclick=()=>{if(safeStore.get(questKey)==='done')return;xp=Math.min(1000000,xp+10);safeStore.set('sr-xp',xp);safeStore.set(questKey,'done');questRender()};
function networkRender(){const on=navigator.onLine;$('networkStatus').textContent=on?'● オンライン（端末判定）':'● オフライン';$('networkStatus').classList.toggle('offline',!on)}window.addEventListener('online',networkRender);window.addEventListener('offline',networkRender);networkRender();
function showUpdate(reg){const n=$('updateNotice');if(!n)return;n.hidden=false;n.setAttribute('role','button');n.tabIndex=0;n.title='クリックして最新版を適用';const apply=()=>{if(reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});else location.reload()};n.onclick=apply;n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();apply()}}}
if('serviceWorker'in navigator){window.addEventListener('load',async()=>{try{const reg=await navigator.serviceWorker.register('./sw.js');if(reg.waiting)showUpdate(reg);reg.addEventListener('updatefound',()=>{const w=reg.installing;if(!w)return;w.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller)showUpdate(reg)})});navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload())}catch{$('pwaStatus').textContent='オフライン機能の登録に失敗しました'}})}
renderAdmin();renderNeeds();const params=new URLSearchParams(location.search);const urlLayers=(params.get('layers')||'').split(',').filter(x=>allowedLayers.has(x));if(urlLayers.length)activeLayers=new Set(urlLayers);const zones=[...document.querySelectorAll('[data-zone]')].map(b=>b.dataset.zone);if(zones.includes(params.get('zone')))selectedZone=params.get('zone');if(future[params.get('year')])year=params.get('year');if(['基準','改善','課題'].includes(params.get('scenario')))scenario=params.get('scenario');const savedSearch=safeStore.get('sr-search','');$('siteSearch').value=savedSearch;applySearch(savedSearch);renderTwin();futureRender();questRender();const savedView=safeStore.get('sr-view','admin');setView(['admin','needs','dx'].includes(savedView)?savedView:'admin');
