'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const data={
'転入・住民票':{building:'中庁舎',floor:'1F',counter:'市民系窓口候補',docs:['本人確認書類','手続内容に応じた関係書類'],steps:['目的を確認','中庁舎1Fを確認','案内表示で窓口候補へ','正式要件を公式ページで確認']},
'税':{building:'中庁舎',floor:'1F',counter:'税系窓口候補',docs:['本人確認書類','申請内容に応じた書類'],steps:['税の種類を確認','中庁舎1Fへ','担当窓口候補を確認','正式要件を公式確認']},
'福祉':{building:'北庁舎',floor:'1F',counter:'福祉系窓口候補',docs:['制度により異なります'],steps:['相談内容を整理','北庁舎1Fへ','福祉・介護等の窓口候補を確認','必要制度を公式確認']},
'議会':{building:'北庁舎',floor:'5F',counter:'議会関連エリア',docs:['傍聴等は公式案内を確認'],steps:['議会情報を確認','北庁舎5Fを確認','受付・傍聴条件を確認','最新日程を公式確認']},
'相談':{building:'全体',floor:'1F',counter:'総合案内・担当課候補',docs:['相談内容により異なります'],steps:['相談内容を整理','総合案内・担当課候補を確認','該当棟・階へ移動','次行動を公式確認']}}
const buildings=['中庁舎','北庁舎','南庁舎','全体'],floors=['1F','2F','3F','4F','5F'];let purpose='転入・住民票',building='中庁舎',floor='1F';
function syncUrl(){const u=new URL(location.href);u.searchParams.set('purpose',purpose);u.searchParams.set('building',building);u.searchParams.set('floor',floor);history.replaceState(null,'',u)}
function mismatch(){const d=data[purpose];return (d.building!=='全体'&&building!==d.building)||floor!==d.floor}
function render(){const d=data[purpose],warn=mismatch();$('title').textContent=building+' '+floor;$('purposeTitle').textContent=purpose+' / '+d.counter+(warn?' ※手動選択中':'');$('route').innerHTML=d.steps.map((s,i)=>`<span class="num">${i+1}</span><div>${esc(s)}</div>`).join('');$('docs').innerHTML='<strong>必要書類の例（正式確認必須）</strong>'+d.docs.map(x=>`<div class="doc"><b>✓ ${esc(x)}</b><small>正式要件は市公式情報を確認</small></div>`).join('')+(warn?`<div class="doc"><b>⚠ 目的の推奨位置と現在の選択が異なります</b><small>${esc(purpose)}の推奨は ${esc(d.building)} ${esc(d.floor)}。現在は ${esc(building)} ${esc(floor)} です。</small></div>`:'');document.querySelectorAll('.buildingBtn').forEach(b=>{const on=b.dataset.building===building;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.tabIndex=on?0:-1});document.querySelectorAll('.floorBtn').forEach(b=>{const on=b.dataset.floor===floor;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.tabIndex=on?0:-1});document.querySelectorAll('.purposeBtn').forEach(b=>{const on=b.dataset.purpose===purpose;b.classList.toggle('active',on);b.setAttribute('aria-pressed',String(on));b.tabIndex=on?0:-1});syncUrl()}
function choosePurpose(p){if(!data[p])return;purpose=p;building=data[p].building;floor=data[p].floor;render()}
function bindArrow(selector,choose){const items=[...document.querySelectorAll(selector)];items.forEach((b,i)=>b.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();let n=i;if(e.key==='ArrowRight')n=(i+1)%items.length;if(e.key==='ArrowLeft')n=(i-1+items.length)%items.length;if(e.key==='Home')n=0;if(e.key==='End')n=items.length-1;items[n].focus();choose(items[n])}))}
document.querySelectorAll('.purposeBtn').forEach(b=>b.onclick=()=>choosePurpose(b.dataset.purpose));document.querySelectorAll('.buildingBtn').forEach(b=>b.onclick=()=>{if(buildings.includes(b.dataset.building)){building=b.dataset.building;render()}});document.querySelectorAll('.floorBtn').forEach(b=>b.onclick=()=>{if(floors.includes(b.dataset.floor)){floor=b.dataset.floor;render()}});document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>choosePurpose(b.dataset.pin));bindArrow('.purposeBtn',b=>choosePurpose(b.dataset.purpose));bindArrow('.buildingBtn',b=>{building=b.dataset.building;render()});bindArrow('.floorBtn',b=>{floor=b.dataset.floor;render()});
function answer(){const q=$('q').value.trim(),d=data[purpose];$('answer').innerHTML=`<strong>${esc(purpose)}</strong><br>${esc(building)} ${esc(floor)} / ${esc(d.counter)}。${q?'質問「'+esc(q)+'」について、':''}${mismatch()?'現在位置は推奨位置と異なります。':''}この画面は案内候補です。正式な窓口・必要書類・受付条件は公式ページで確認してください。`;$('answer').classList.add('show')}
$('ask').onclick=answer;$('q').onkeydown=e=>{if(e.key==='Enter')answer()};$('toAi').onclick=()=>{$('q').value=purpose+'の必要書類と窓口を知りたい';location.hash='ai';answer()};
async function copyCurrentUrl(){try{if(navigator.share){await navigator.share({title:'袖ケ浦市庁舎 Digital Twin',url:location.href});$('shareStatus').textContent='共有画面を開きました。';return}if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(location.href)}else{const t=document.createElement('textarea');t.value=location.href;t.setAttribute('readonly','');t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();const ok=document.execCommand('copy');t.remove();if(!ok)throw new Error('copy failed')}$('shareStatus').textContent='現在の選択状態URLをコピーしました。'}catch(e){if(e&&e.name==='AbortError'){$('shareStatus').textContent='共有をキャンセルしました。';return}$('shareStatus').textContent='共有できませんでした。ブラウザのURLを共有してください。'}}$('copyLink').onclick=copyCurrentUrl;
const params=new URLSearchParams(location.search),p=params.get('purpose'),b=params.get('building'),f=params.get('floor');if(p&&data[p])purpose=p;if(b&&buildings.includes(b))building=b;if(f&&floors.includes(f))floor=f;render();
